const Actions = {
    FETCH_TOKEN_START : "FETCH_TOKEN_START",
    FETCH_TOKEN_SUCCESS : "FETCH_TOKEN_SUCCESS",
    FETCH_TOKEN_FAILURE : "FETCH_TOKEN_FAILURE",

    FETCH_USER_START : "FETCH_USER_START",
    FETCH_USER_SUCCESS : "FETCH_USER_SUCCESS",
    FETCH_USER_FAILURE : "FETCH_USER_FAILURE",

    FETCH_TASKS_START : "FETCH_TASKS_START",
    FETCH_TASKS_SUCCESS : "FETCH_TASKS_SUCCESS",
    FETCH_TASKS_FAILURE : "FETCH_TASKS_FAILURE",

    ADD_TASKS_START : "ADD_TASKS_START",
    ADD_TASKS_SUCCESS : "ADD_TASKS_SUCCESS",
    ADD_TASKS_FAILURE : "ADD_TASKS_FAILURE",

    UPDATE_TASKS_START : "UPDATE_TASKS_START",
    UPDATE_TASKS_SUCCESS : "UPDATE_TASKS_SUCCESS",
    UPDATE_TASKS_FAILURE : "UPDATE_TASKS_FAILURE",

    DELETE_TASKS : "DELETE_TASKS",
    DELETE_TASKS_FAILURE : "DELETE_TASKS_FAILURE",

}

export default Actions;